### ISSUE TITLE
NameError uninitialized constant Shotstack::Output::FPS

### ISSUE THREAD

**Issue by gaR-metafy** [shotstack/shotstack-sdk-ruby#13]
I'm hitting this error using `EditApi.get_render` on version 0.1.10
![image](https://user-images.githubusercontent.com/89018299/158568304-0310b933-07b3-4086-8a2f-b6baa2d9344a.png)

**Comment by ghost** [comment]
The Ruby SDK has now been updated with a fix. Thanks for the report!
