### ISSUE TITLE
The AudioAsset model is missing.

### ISSUE THREAD

**Issue by anandvc** [shotstack/shotstack-sdk-ruby#2]
Need a way to use `AudioAsset` https://shotstack.io/docs/api/index.html?ruby#tocsaudioasset

**Comment by jeffski** [comment]
The Ruby SDK has now been bought up to date with all the latest features, along with some new features we are releasing soon.

Also not that this update changes `Shotstack::DefaultApi` to `Shotstack::EndpointsApi` which will need to be updated in existing applications.
